import numpy as np


ab_lookup = {'name': ["Carrying Case for FreeStyle InsuLinx System",
                   "Carrying Case for FreeStyle Precision Neo System",
                   "Data Cable and Charging Adapter for FreeStyle Libre 14 Day System",
                   "Data Cable For FreeStyle Precision Neo and FreeStyle Libre 14 day Systems",
                   "Ensure Enlive",
                   "Ensure Rapid Hydration Electrolyte Powder Packs",
                   "FreeStyle Carrying Case",
                   "FreeStyle Control Solution",
                   "FreeStyle Data Cable",
                   "FreeStyle Lancets",
                   "FreeStyle Lancing Device II",
                   "FreeStyle Log Books / 100 pack",
                   "FreeStyle Precision Neo Blood Glucose Monitoring System",
                   "Glucerna Mini Treats", 	"Glucerna Snack Bars",
                   "Meter Replacement Batteries",
                   "Pedialyte",
                   "Pedialyte",
                   "Pedialyte",
                   "Pedialyte",
                   "Pedialyte",
                   "Pedialyte AdvancedCare",
                   "Pedialyte AdvancedCare",
                   "Pedialyte AdvancedCare",
                   "Pedialyte AdvancedCare Plus",
                   "Pedialyte AdvancedCare Plus",
                   "Pedialyte AdvancedCare Plus Hydration Station Multipack",
                   "Pedialyte AdvancedCare Plus Powder Packs",
                   "Pedialyte AdvancedCare Plus Powder Packs",
                   "Pedialyte Hydration Station Multipack",
                   "Pedialyte Powder Packs",
                   "Pedialyte Powder Packs",
                   "Pedialyte Powder Packs",
                   "Pedialyte Powder Packs",
                   "Pedialyte Sparkling Rush Powder Packs",
                   "Pedialyte Sparkling Rush Powder Packs",
                   "Similac Breast Milk Storage Bottle Caps",
                   "Similac Human Milk Fortifier Powder",
                   "Similac Human Milk Fortifier Powder",
                   "Similac Volu-Feed Nurser",
                   "ZonePerfect Macros Bar",
                   "ZonePerfect Macros Bar",
                   "ZonePerfect Nutrition Bar",
                   "ZonePerfect Nutrition Bar",
                   "ZonePerfect Nutrition Bar",
                   "ZonePerfect Nutrition Bar",
                   "ZonePerfect Nutrition Bar",
                   "ZonePerfect Nutrition Bar",
                   "ZonePerfect Nutrition Bar",
                   "ZonePerfect Nutrition Bar",
                   "Similac Slow Flow Nipple and Ring",
                   "Similac Infant Nipple and Ring",
                   "Similac Premature Nipple and Ring",
                   "Similac Orthodontic Nipple and Ring",
                   "Cooler Insert with 2 Freezable Ice Packs",
                   "FreeStyle Precision Neo Starter Pack",
                   "FreeStyle Precision Neo Blood Glucose Test Strips / 50 count",
                   "FreeStyle Precision Neo Blood Glucose Test Strips / 25 count",
                   "FreeStyle Log Books / 6 pack"],
          'item_type': ["SKU#:21372",
                        "SKU#:25189",
                        "SKU#:7161301",
                        "SKU#:213732",
                        "SKU#:64293",
                        "SKU#:67475",
                        "SKU#:7037301",
                        "SKU#:1400204",
                        "SKU#:7085102",
                        "SKU#:1300170",
                        "SKU#:7158201",
                        "SKU#:22309p100",
                        "SKU#:7517583",
                        "SKU#:66906",
                        "SKU#:66884",
                        "SKU#:7037401p5",
                        "SKU#:00365",
                        "SKU#:67461",
                        "SKU#:59892",
                        "SKU#:59892p4",
                        "SKU#:51752e",
                        "SKU#:64301",
                        "SKU#:63059",
                        "SKU#:64307e",
                        "SKU#:67434",
                        "SKU#:66645e",
                        "SKU#:67287p80",
                        "SKU#:67426p6",
                        "SKU#:67426",
                        "SKU#:67285p80",
                        "SKU#:64598",
                        "SKU#:56090",
                        "SKU#:56090p8",
                        "SKU#:64172p6",
                        "SKU#:67220p6",
                        "SKU#:67225",
                        "SKU#:54080",
                        "SKU#:54598p50",
                        "SKU#:54598",
                        "SKU#:00180",
                        "SKU#:67500",
                        "SKU#:67500p12",
                        "SKU#:63225p12",
                        "SKU#:63282p12",
                        "SKU#:63305",
                        "SKU#:63269",
                        "SKU#:66040p12",
                        "SKU#:63304",
                        "SKU#:63505",
                        "SKU#:66040",
                        "SKU#:53894p50",
                        "SKU#:00079p50",
                        "SKU#:00094",
                        "SKU#:53560",
                        "SKU#:53568",
                        "SKU#:FSMTS50",
                        "SKU#:7157975",
                        "SKU#:7157775",
                        "SKU#:22309p6"],
          "product_format": ["carrying case",
                             "carrying case",
                             "device",
                             "device",
                             "bottle",
                             "packets",
                             "carrying case",
                             "solution",
                             "device",
                             "lancet",
                             "device",
                             "log book",
                             "device",
                             "packets",
                             "bars",
                             "device",
                             "bottle",
                             "bottle",
                             "bottle",
                             "bottle",
                             "bottle",
                             "bottle",
                             "bottle",
                             "bottle",
                             "bottle",
                             "bottle",
                             "packets",
                             "packets",
                             "packets",
                             "packets",
                             "packets",
                             "packets",
                             "packets",
                             "packets",
                             "packets",
                             "packets",
                             "bottle",
                             "packets",
                             "packets",
                             "bottle",
                             "bars",
                             "bars",
                             "bars",
                             "bars",
                             "bars",
                             "bars",
                             "bars",
                             "bars",
                             "bars",
                             "bars",
                             "device",
                             "device",
                             "device",
                             "device",
                             "ice pack",
                             "device",
                             "strips",
                             "strips",
                             "log book"],
          "number_in_case": [1,
                             1,
                             1,
                             1,
                             16,
                             6,
                             1,
                             2,
                             1,
                             100,
                             1,
                             100,
                             1,
                             24,
                             20,
                             5,
                             8,
                             4,
                             48,
                             4,
                             1,
                             4,
                             8,
                             1,
                             4,
                             1,
                             80,
                             6,
                             6,
                             80,
                             6,
                             8,
                             8,
                             6,
                             6,
                             6,
                             250,
                             50,
                             150,
                             100,
                             36,
                             12,
                             12,
                             12,
                             30,
                             30,
                             12,
                             36,
                             36,
                             36,
                             np.nan,
                             np.nan,
                             np.nan,
                             np.nan,
                             2,
                             np.nan,
                             50,
                             25,
                             6],
          "product_weight_numeric": [np.nan,
                                     np.nan,
                                     np.nan,
                                     np.nan,
                                     8,
                                     0.6,
                                     np.nan,
                                     4,
                                     np.nan,
                                     np.nan,
                                     np.nan,
                                     np.nan,
                                     np.nan,
                                     0.7,
                                     1.4,
                                     np.nan,
                                     1,
                                     1,
                                     2,
                                     2,
                                     np.nan,
                                     1,
                                     1,
                                     np.nan,
                                     1,
                                     np.nan,
                                     0.6,
                                     0.6,
                                     0.6,
                                     0.6,
                                     0.6,
                                     0.3,
                                     0.3,
                                     0.6,
                                     0.6,
                                     0.6,
                                     np.nan,
                                     0.9,
                                     0.9,
                                     np.nan,
                                     1.76,
                                     1.76,
                                     1.58,
                                     1.76,
                                     1.58,
                                     1.76,
                                     1.41,
                                     1.76,
                                     1.58,
                                     1.41,
                                     np.nan,
                                     np.nan,
                                     np.nan,
                                     np.nan,
                                     np.nan,
                                     np.nan,
                                     np.nan,
                                     np.nan,
                                     np.nan],
          "product_weight_metric": ["",
                                    "",
                                    "",
                                    "",
                                    "oz",
                                    "oz",
                                    "",
                                    "ml",
                                    "",
                                    "",
                                    "",
                                    "",
                                    "",
                                    "oz",
                                    "oz",
                                    "",
                                    "L",
                                    "L",
                                    "oz",
                                    "oz",
                                    "",
                                    "L",
                                    "L",
                                    "",
                                    "L",
                                    "",
                                    "oz",
                                    "oz",
                                    "oz",
                                    "oz",
                                    "oz",
                                    "oz",
                                    "oz",
                                    "oz",
                                    "oz",
                                    "oz",
                                    "",
                                    "g",
                                    "g",
                                    "",
                                    "oz",
                                    "oz",
                                    "oz",
                                    "oz",
                                    "oz",
                                    "oz",
                                    "oz",
                                    "oz",
                                    "oz",
                                    "oz",
                                    "",
                                    "",
                                    "",
                                    "",
                                    "",
                                    "",
                                    "",
                                    "",
                                    ""]}