
PRODUCT_INFORMATION = {'url':'',
                        'name':'',
                        'price':'',
                        'size_or_weight':'',
                        'availability':'',	
                        'item_type':'',
                        'description':'',
                        'ingredients':'',
                        'allergin_info':'',
                        'serving_size_1':'',                        
                        'serving_size_2':'',
                        'serving_size_3':'',
                        'serving_size_4':'',
                        'serving_size_5':'',
                        'footnotes':'',
                        'nutrient_table_1': '',
                        'nutrient_table_2': '',
                        'nutrient_table_3': '',
                        'nutrient_table_4': '',
                        'nutrient_table_5': '',
                        'vitamin_table_1':'',
                        'vitamin_table_2':'',
                        'vitamin_table_3':'',
                        'vitamin_table_4':'',
                        'vitamin_table_5':'',
                        'mineral_table_1':'',
                        'mineral_table_2':'',
                        'mineral_table_3':'',
                        'mineral_table_4':'',
                        'mineral_table_5':'',
                        'Sizes':'',
                        'Form':'',
                        'Flavours':'',
                        'clinical indications': '',
                        'benefits':'' ,
                        'clinical_indications':'' ,
                        'feature_table_rows':'',
                        'usage':'',
                        'entry_date':''}


PRODUCT_INFORMATION = {'url':[],
                    'name':[],
                    'category':[],
                    'brand':[],
                    'pack_size':[],
                    'case_size':[],
                    'indications':[],
                    'precautions':[],
                    'directions_for_use':[],
                    'shelf_life':[],
                    'flavours':[]}